/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket;

import com.mysql.jdbc.Connection; // kode untuk membuat koneksi ke database
import java.sql.ResultSet; // Menjalankan query dan menyimpan hasilnya dalam ResultSet
import java.sql.SQLException; //mendeklarasikan bahwa kelas program Anda akan menggunakan kelas 
import java.sql.Statement; //Membuat objek Statement
import javax.swing.JOptionPane; //Digunakan untuk mengimpor kelas JOptionPane dari paket javax.swing.

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {

    Connection con; //digunakan untuk menghubungkan program kita dengan database. 
    Statement st; //digunakan untuk mengirimkan perintah (query) ke database.
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        CmbHak = new javax.swing.JComboBox<>();
        btnexit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 194, 480, 40));

        password.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 314, 480, 40));

        btnlogin.setBackground(new java.awt.Color(0,0,0,0));
        btnlogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        login.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 134, 50));

        CmbHak.setBackground(new java.awt.Color(126, 181, 232));
        CmbHak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CmbHak.setForeground(new java.awt.Color(126, 181, 232));
        CmbHak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Penumpang" }));
        login.add(CmbHak, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 470, 510, 43));

        btnexit.setBackground(new java.awt.Color(0,0,0,0));
        btnexit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        login.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 130, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/LOGIN KERETA (1).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1220, 720));

        jRadioButton1.setText("jRadioButton1");
        login.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        //
        try{
            String pass = new String(password.getPassword());
            con = Koneksi.getKoneksi();
            String sql = "SELECT * FROM admin WHERE username='"+username.getText()+"' And password='"+pass+"'";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                if(username.getText().equals(rs.getString("username")) && pass.equals(rs.getString("password"))){
               new Home().setVisible(true);
                dispose();
                }
            }else{
                    JOptionPane.showMessageDialog(null, "Gagal Login Oi");
                }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        //digunakan untuk memeriksa kecocokan username dan password pengguna dengan data yang tersimpan di database, 
        //lalu memberikan akses ke halaman utama aplikasi jika cocok, atau menampilkan pesan kesalahan jika tidak cocok.
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
  if (JOptionPane.showConfirmDialog(this, "Exit Program ?", "Konfimasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
        System.exit(0);            // TODO add your handling code here:
    }//GEN-LAST:event_btnexitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
            //digunakan untuk memastikan jendela login (atau komponen grafis lainnya)
            //muncul dengan benar dan lancar pada aplikasi Java
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbHak;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPanel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
